---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      QUERY_MAXIMUM_RESULTS: '100'

      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
      # OLLAMA_HOST: 'http://localhost:11434'    
    mem_limit: "2g"         # tope de RAM
    memswap_limit: "2g"     # tope de RAM+swap
    cpus: "2.0"             # limita a 2 vCPUs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:8080/v1/.well-known/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  weaviate_data:
...